// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: dbapi.proto

package golang

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MediaAndSessionClient is the client API for MediaAndSession service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MediaAndSessionClient interface {
	GetSession(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Session, error)
	SetSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionID, error)
	GetMedia(ctx context.Context, in *MediaID, opts ...grpc.CallOption) (*Media, error)
	SetMedia(ctx context.Context, in *Media, opts ...grpc.CallOption) (*MediaID, error)
}

type mediaAndSessionClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaAndSessionClient(cc grpc.ClientConnInterface) MediaAndSessionClient {
	return &mediaAndSessionClient{cc}
}

func (c *mediaAndSessionClient) GetSession(ctx context.Context, in *SessionID, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/dbapis.MediaAndSession/GetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaAndSessionClient) SetSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionID, error) {
	out := new(SessionID)
	err := c.cc.Invoke(ctx, "/dbapis.MediaAndSession/SetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaAndSessionClient) GetMedia(ctx context.Context, in *MediaID, opts ...grpc.CallOption) (*Media, error) {
	out := new(Media)
	err := c.cc.Invoke(ctx, "/dbapis.MediaAndSession/GetMedia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaAndSessionClient) SetMedia(ctx context.Context, in *Media, opts ...grpc.CallOption) (*MediaID, error) {
	out := new(MediaID)
	err := c.cc.Invoke(ctx, "/dbapis.MediaAndSession/SetMedia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaAndSessionServer is the server API for MediaAndSession service.
// All implementations must embed UnimplementedMediaAndSessionServer
// for forward compatibility
type MediaAndSessionServer interface {
	GetSession(context.Context, *SessionID) (*Session, error)
	SetSession(context.Context, *Session) (*SessionID, error)
	GetMedia(context.Context, *MediaID) (*Media, error)
	SetMedia(context.Context, *Media) (*MediaID, error)
	mustEmbedUnimplementedMediaAndSessionServer()
}

// UnimplementedMediaAndSessionServer must be embedded to have forward compatible implementations.
type UnimplementedMediaAndSessionServer struct {
}

func (UnimplementedMediaAndSessionServer) GetSession(context.Context, *SessionID) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedMediaAndSessionServer) SetSession(context.Context, *Session) (*SessionID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSession not implemented")
}
func (UnimplementedMediaAndSessionServer) GetMedia(context.Context, *MediaID) (*Media, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedMediaAndSessionServer) SetMedia(context.Context, *Media) (*MediaID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMedia not implemented")
}
func (UnimplementedMediaAndSessionServer) mustEmbedUnimplementedMediaAndSessionServer() {}

// UnsafeMediaAndSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaAndSessionServer will
// result in compilation errors.
type UnsafeMediaAndSessionServer interface {
	mustEmbedUnimplementedMediaAndSessionServer()
}

func RegisterMediaAndSessionServer(s grpc.ServiceRegistrar, srv MediaAndSessionServer) {
	s.RegisterService(&MediaAndSession_ServiceDesc, srv)
}

func _MediaAndSession_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaAndSessionServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.MediaAndSession/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaAndSessionServer).GetSession(ctx, req.(*SessionID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaAndSession_SetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaAndSessionServer).SetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.MediaAndSession/SetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaAndSessionServer).SetSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaAndSession_GetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MediaID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaAndSessionServer).GetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.MediaAndSession/GetMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaAndSessionServer).GetMedia(ctx, req.(*MediaID))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaAndSession_SetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Media)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaAndSessionServer).SetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.MediaAndSession/SetMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaAndSessionServer).SetMedia(ctx, req.(*Media))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaAndSession_ServiceDesc is the grpc.ServiceDesc for MediaAndSession service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaAndSession_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbapis.MediaAndSession",
	HandlerType: (*MediaAndSessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSession",
			Handler:    _MediaAndSession_GetSession_Handler,
		},
		{
			MethodName: "SetSession",
			Handler:    _MediaAndSession_SetSession_Handler,
		},
		{
			MethodName: "GetMedia",
			Handler:    _MediaAndSession_GetMedia_Handler,
		},
		{
			MethodName: "SetMedia",
			Handler:    _MediaAndSession_SetMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dbapi.proto",
}
