// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: dbapi.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DBreqClient is the client API for DBreq service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBreqClient interface {
	GetUser(ctx context.Context, opts ...grpc.CallOption) (DBreq_GetUserClient, error)
	SetUser(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*UserID, error)
	GetSession(ctx context.Context, opts ...grpc.CallOption) (DBreq_GetSessionClient, error)
	SetSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionID, error)
	GetMedia(ctx context.Context, opts ...grpc.CallOption) (DBreq_GetMediaClient, error)
	SetMedia(ctx context.Context, in *Media, opts ...grpc.CallOption) (*MediaID, error)
}

type dBreqClient struct {
	cc grpc.ClientConnInterface
}

func NewDBreqClient(cc grpc.ClientConnInterface) DBreqClient {
	return &dBreqClient{cc}
}

func (c *dBreqClient) GetUser(ctx context.Context, opts ...grpc.CallOption) (DBreq_GetUserClient, error) {
	stream, err := c.cc.NewStream(ctx, &DBreq_ServiceDesc.Streams[0], "/dbapis.DBreq/GetUser", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBreqGetUserClient{stream}
	return x, nil
}

type DBreq_GetUserClient interface {
	Send(*UserID) error
	Recv() (*User, error)
	grpc.ClientStream
}

type dBreqGetUserClient struct {
	grpc.ClientStream
}

func (x *dBreqGetUserClient) Send(m *UserID) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dBreqGetUserClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBreqClient) SetUser(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*UserID, error) {
	out := new(UserID)
	err := c.cc.Invoke(ctx, "/dbapis.DBreq/SetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBreqClient) GetSession(ctx context.Context, opts ...grpc.CallOption) (DBreq_GetSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &DBreq_ServiceDesc.Streams[1], "/dbapis.DBreq/GetSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBreqGetSessionClient{stream}
	return x, nil
}

type DBreq_GetSessionClient interface {
	Send(*SessionID) error
	Recv() (*Session, error)
	grpc.ClientStream
}

type dBreqGetSessionClient struct {
	grpc.ClientStream
}

func (x *dBreqGetSessionClient) Send(m *SessionID) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dBreqGetSessionClient) Recv() (*Session, error) {
	m := new(Session)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBreqClient) SetSession(ctx context.Context, in *Session, opts ...grpc.CallOption) (*SessionID, error) {
	out := new(SessionID)
	err := c.cc.Invoke(ctx, "/dbapis.DBreq/SetSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBreqClient) GetMedia(ctx context.Context, opts ...grpc.CallOption) (DBreq_GetMediaClient, error) {
	stream, err := c.cc.NewStream(ctx, &DBreq_ServiceDesc.Streams[2], "/dbapis.DBreq/GetMedia", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBreqGetMediaClient{stream}
	return x, nil
}

type DBreq_GetMediaClient interface {
	Send(*MediaID) error
	Recv() (*Media, error)
	grpc.ClientStream
}

type dBreqGetMediaClient struct {
	grpc.ClientStream
}

func (x *dBreqGetMediaClient) Send(m *MediaID) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dBreqGetMediaClient) Recv() (*Media, error) {
	m := new(Media)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBreqClient) SetMedia(ctx context.Context, in *Media, opts ...grpc.CallOption) (*MediaID, error) {
	out := new(MediaID)
	err := c.cc.Invoke(ctx, "/dbapis.DBreq/SetMedia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBreqServer is the server API for DBreq service.
// All implementations must embed UnimplementedDBreqServer
// for forward compatibility
type DBreqServer interface {
	GetUser(DBreq_GetUserServer) error
	SetUser(context.Context, *Auth) (*UserID, error)
	GetSession(DBreq_GetSessionServer) error
	SetSession(context.Context, *Session) (*SessionID, error)
	GetMedia(DBreq_GetMediaServer) error
	SetMedia(context.Context, *Media) (*MediaID, error)
	mustEmbedUnimplementedDBreqServer()
}

// UnimplementedDBreqServer must be embedded to have forward compatible implementations.
type UnimplementedDBreqServer struct {
}

func (UnimplementedDBreqServer) GetUser(DBreq_GetUserServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedDBreqServer) SetUser(context.Context, *Auth) (*UserID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUser not implemented")
}
func (UnimplementedDBreqServer) GetSession(DBreq_GetSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedDBreqServer) SetSession(context.Context, *Session) (*SessionID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSession not implemented")
}
func (UnimplementedDBreqServer) GetMedia(DBreq_GetMediaServer) error {
	return status.Errorf(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedDBreqServer) SetMedia(context.Context, *Media) (*MediaID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMedia not implemented")
}
func (UnimplementedDBreqServer) mustEmbedUnimplementedDBreqServer() {}

// UnsafeDBreqServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBreqServer will
// result in compilation errors.
type UnsafeDBreqServer interface {
	mustEmbedUnimplementedDBreqServer()
}

func RegisterDBreqServer(s grpc.ServiceRegistrar, srv DBreqServer) {
	s.RegisterService(&DBreq_ServiceDesc, srv)
}

func _DBreq_GetUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DBreqServer).GetUser(&dBreqGetUserServer{stream})
}

type DBreq_GetUserServer interface {
	Send(*User) error
	Recv() (*UserID, error)
	grpc.ServerStream
}

type dBreqGetUserServer struct {
	grpc.ServerStream
}

func (x *dBreqGetUserServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dBreqGetUserServer) Recv() (*UserID, error) {
	m := new(UserID)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DBreq_SetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBreqServer).SetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.DBreq/SetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBreqServer).SetUser(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBreq_GetSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DBreqServer).GetSession(&dBreqGetSessionServer{stream})
}

type DBreq_GetSessionServer interface {
	Send(*Session) error
	Recv() (*SessionID, error)
	grpc.ServerStream
}

type dBreqGetSessionServer struct {
	grpc.ServerStream
}

func (x *dBreqGetSessionServer) Send(m *Session) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dBreqGetSessionServer) Recv() (*SessionID, error) {
	m := new(SessionID)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DBreq_SetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBreqServer).SetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.DBreq/SetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBreqServer).SetSession(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBreq_GetMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DBreqServer).GetMedia(&dBreqGetMediaServer{stream})
}

type DBreq_GetMediaServer interface {
	Send(*Media) error
	Recv() (*MediaID, error)
	grpc.ServerStream
}

type dBreqGetMediaServer struct {
	grpc.ServerStream
}

func (x *dBreqGetMediaServer) Send(m *Media) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dBreqGetMediaServer) Recv() (*MediaID, error) {
	m := new(MediaID)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DBreq_SetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Media)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBreqServer).SetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbapis.DBreq/SetMedia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBreqServer).SetMedia(ctx, req.(*Media))
	}
	return interceptor(ctx, in, info, handler)
}

// DBreq_ServiceDesc is the grpc.ServiceDesc for DBreq service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBreq_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbapis.DBreq",
	HandlerType: (*DBreqServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUser",
			Handler:    _DBreq_SetUser_Handler,
		},
		{
			MethodName: "SetSession",
			Handler:    _DBreq_SetSession_Handler,
		},
		{
			MethodName: "SetMedia",
			Handler:    _DBreq_SetMedia_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUser",
			Handler:       _DBreq_GetUser_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetSession",
			Handler:       _DBreq_GetSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetMedia",
			Handler:       _DBreq_GetMedia_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dbapi.proto",
}
